// ================================================================
// KnowledgeBase Schema Template
//
// This is the canonical .kbs file content pushed to every analysed
// repository. It defines what a .kb file must contain, documents
// every field, and serves as the contract between this tool and any
// AI agent that later reads the .kb.
// ================================================================

export const KBS_VERSION = "1.0";

export const KBS_TEMPLATE = `# ================================================================
# .kbs — KnowledgeBase Schema  ·  v${KBS_VERSION}
# Generated by KnowledgeBase (https://knowledge-base-flame-sigma.vercel.app)
# ================================================================
#
# This file defines the structure and documentation for .kb files.
# A .kb file is the single authoritative reference an AI agent reads
# before starting any work on this repository.
#
# Reading guide:
#   [REQUIRED]  Field must be present in every .kb file.
#   [OPTIONAL]  Fill if applicable; omit or set to null if not.
#   Values in quotes describe what content belongs in that field.
#   The schema is intentionally human-readable — it IS the docs.
# ================================================================

_meta:
  schema_version: "${KBS_VERSION}"
  description: >
    The KnowledgeBase Schema (.kbs) defines what every .kb file must contain.
    A .kb file answers the questions an AI agent needs answered before touching
    any code: what is this system, how is it structured, where do things live,
    what are the rules, and what is the current state of work?
    Read the .kb before reading any source file.

# ──────────────────────────────────────────────────────────────────────
# PROJECT — Identity and purpose
# Purpose: Orient an agent (or human) who has never seen this codebase.
# ──────────────────────────────────────────────────────────────────────
project:
  name: >
    [REQUIRED] The canonical human-readable project name.
    Use the name people call it in conversation, not a slug.

  tagline: >
    [REQUIRED] ≤15 words. What it does and who it's for.
    Write it so a non-technical stakeholder immediately understands.

  description: >
    [REQUIRED] 2–5 sentences. What problem does this solve? Who uses it?
    What is the core value proposition? Include anything a new contributor
    needs to understand the product intent before reading code.

  status: >
    [REQUIRED] Current lifecycle stage.
    Allowed values: concept | development | beta | production | maintenance | deprecated

  url: >
    [OPTIONAL] Primary URL where the project is running.
    Omit if not deployed or not publicly accessible.

  repository: >
    [REQUIRED] Full GitHub repository URL.

  owner: >
    [OPTIONAL] Person or team responsible. Helps agents know who to
    consider as the decision-maker when trade-offs arise.

# ──────────────────────────────────────────────────────────────────────
# ARCHITECTURE — How the system is designed
# Purpose: Let an agent understand the system shape before reading code.
#          A well-written overview prevents category errors (e.g., looking
#          for a database that doesn't exist, or missing a key indirection).
# ──────────────────────────────────────────────────────────────────────
architecture:
  overview: >
    [REQUIRED] 3–8 sentences. Describe the system architecture: what the
    major components are, how they relate, and how data flows through the
    system. Include the primary request/processing pattern. An agent reading
    this should immediately know where to look for any given type of logic
    and understand why the system is shaped the way it is.

  style: >
    [REQUIRED] Primary architectural style.
    Allowed values: monolith | microservices | serverless | jamstack |
    spa | mpa | event-driven | library | cli | hybrid

  decisions:
    # Each entry captures one key architectural decision.
    # Focus on choices that are non-obvious or that constrain future work.
    - decision: >
        [REQUIRED] What was decided — state it concretely.
        Example: "No database — all persistent state stored as files in
        the user's own Google Drive account."
      rationale: >
        [REQUIRED] Why this decision was made. What problem did it solve
        or what constraint did it satisfy?
      tradeoffs: >
        [REQUIRED] What was given up or accepted. An honest assessment of
        the downsides helps agents understand the boundaries of the design.

  constraints: >
    [OPTIONAL] Hard constraints the system must operate within.
    These are non-negotiable and shape every subsequent decision.
    Example: "Must run serverless (Vercel Edge/Lambda). No persistent
    server-side state. All user data must stay in the user's own storage."

  non_goals: >
    [OPTIONAL] What this system explicitly does NOT do.
    Critical for agents to avoid building features outside intended scope.

# ──────────────────────────────────────────────────────────────────────
# TECH STACK — What the system is built with
# Purpose: Let an agent immediately know what tools, versions, and
#          patterns are in play without reading any config files.
# ──────────────────────────────────────────────────────────────────────
tech_stack:
  languages:
    # [REQUIRED] List all languages. Primary language first.
    # Example: ["TypeScript", "CSS", "SQL"]
    - "[REQUIRED] Primary language (and version if relevant)"

  runtime: >
    [OPTIONAL] Runtime environment and version.
    Example: "Node.js 20 LTS"

  frameworks:
    - name: "[REQUIRED] Framework name and version"
      purpose: >
        What this framework is responsible for in the system.
        Example: "Next.js 14 App Router — SSR, routing, API routes"

  persistence:
    - name: "[OPTIONAL] Storage solution name"
      type: >
        relational | document | key-value | file | object-storage | cache
      purpose: >
        What data is stored here and why this storage was chosen over
        a more conventional alternative (the 'why' is the important part).

  infrastructure:
    hosting: "[OPTIONAL] Hosting platform and tier. Example: Vercel Pro"
    cdn: "[OPTIONAL] CDN provider if applicable"
    ci_cd: >
      [OPTIONAL] CI/CD platform and what it automates.
      Example: "GitHub Actions — runs typecheck and deploys to Vercel on push to main"
    monitoring: "[OPTIONAL] Error tracking, logging, APM tools in use"

  integrations:
    - name: "[OPTIONAL] External service name"
      purpose: >
        Why this integration exists and what capability it provides.
        Frame as 'without this service, we could not…'
      auth: >
        How authentication with this service works.
        Example: "OAuth 2.0 access token stored in session JWT"
      docs: "[OPTIONAL] URL to the most relevant API documentation"

# ──────────────────────────────────────────────────────────────────────
# CODEBASE — How the repository is organised
# Purpose: Tell an agent where things live so it stops searching and
#          starts reading the right files immediately.
# ──────────────────────────────────────────────────────────────────────
codebase:
  structure: >
    [REQUIRED] Describe the directory and module organisation. What goes
    where and why? Cover: source layout, config files, generated vs
    hand-written code, naming conventions for files. An agent should read
    this and know exactly which directory to search for any given concern.

  entry_points:
    - path: "[REQUIRED] Relative path to a primary entry point"
      description: >
        What this entry point does and what it bootstraps.
        Example: "app/page.tsx — client root, composes all main UI panels"

  critical_files:
    - path: "[OPTIONAL] Relative file path"
      why: >
        Why this file is critical — not obvious from its name or location.
        Example: "types/index.ts — all shared types; add new types here
        before implementing any feature, or the Zod schema will diverge."

  commands:
    dev: "[REQUIRED] Command to start the development server"
    build: "[REQUIRED] Command to create a production build"
    test: "[OPTIONAL] Command to run the test suite. Write 'none' if no tests."
    lint: "[OPTIONAL] Command to lint the codebase"
    typecheck: "[OPTIONAL] Command for static type checking without emit"
    deploy: "[OPTIONAL] How to deploy, if not automatic on push"

  environment:
    setup: >
      [OPTIONAL] Steps to configure a fresh development environment.
      Example: "Copy .env.example to .env.local and fill the required vars."
    required_vars:
      - name: "[REQUIRED if any] Environment variable name"
        description: "What it configures or enables"
        example: "Example value format — never put real secrets here"
    optional_vars:
      - name: "[OPTIONAL] Optional variable name"
        description: "What it enables when set"
        default: "Default behaviour when not set"

# ──────────────────────────────────────────────────────────────────────
# DOMAIN — Core business concepts and rules
# Purpose: Give agents the mental model of the problem being solved
#          before they read implementation code. Without this, agents
#          fix symptoms rather than understanding intent.
# ──────────────────────────────────────────────────────────────────────
domain:
  overview: >
    [OPTIONAL] Brief description of the problem domain. What is the
    business context? Define domain-specific terminology. What mental
    model should an agent build before reading code?

  entities:
    - name: "[REQUIRED] Entity name as used in the code"
      description: "What this represents in the domain"
      location: "File path where it is defined (or primarily used)"
      key_fields: >
        The most important fields and what they mean — especially fields
        whose purpose is not obvious from their name.

  rules:
    # [REQUIRED if any] Critical business invariants that must never be
    # violated. These are not implementation details — they are
    # constraints that reflect real requirements.
    # Example: "EDIT_FILE with confidence < 0.8 must always be blocked.
    # This is a safety gate protecting user data, not a bug to fix."
    - "[REQUIRED if any] Business rule stated as a hard constraint"

  flows:
    - name: "[OPTIONAL] Name of a key business or data flow"
      steps: >
        Step-by-step description. Focus on flows that cross multiple
        components or have non-obvious steps that confuse new contributors.

# ──────────────────────────────────────────────────────────────────────
# API — Public interface of the system
# Purpose: Describe the external-facing contract so agents know what
#          can be called and what behaviour to expect and preserve.
# ──────────────────────────────────────────────────────────────────────
api:
  style: "[OPTIONAL] rest | graphql | grpc | trpc | sdk | none"
  base_url: "[OPTIONAL] Base URL for API calls"

  auth:
    mechanism: >
      [OPTIONAL] How authentication works end-to-end.
      Example: "Next-Auth v5 JWT session via Google OAuth. The access token
      is forwarded from the JWT to every service call on the server."
    notes: >
      [OPTIONAL] Non-obvious auth details: token lifetime, refresh
      behaviour, multi-device considerations, cookie strategy, etc.

  key_routes:
    - route: "[OPTIONAL] Method + path. Example: POST /api/process"
      purpose: >
        What this route does — focus on the business intent (the 'why'),
        not just the mechanical description (the 'what').
      notes: >
        Non-obvious behaviour, important side effects, or constraints.
        What would trip up an agent implementing against this route?

# ──────────────────────────────────────────────────────────────────────
# CONVENTIONS — How code is written in this project
# Purpose: Ensure agents produce idiomatic code that matches the existing
#          codebase style rather than introducing inconsistencies.
# ──────────────────────────────────────────────────────────────────────
conventions:
  style: >
    [OPTIONAL] Coding conventions: naming (camelCase, snake_case, PascalCase),
    file naming, import ordering, comment philosophy, function size limits.
    An agent must follow these exactly to produce idiomatic code.

  patterns:
    - name: "[OPTIONAL] Pattern name"
      description: >
        How and where this pattern is used in this codebase.
        Include a file reference so an agent can see it in context.

  antipatterns:
    # [OPTIONAL] Things explicitly avoided and why. Agents must not
    # introduce these even if they seem reasonable in other contexts.
    - "[OPTIONAL] Antipattern and why it is avoided here"

# ──────────────────────────────────────────────────────────────────────
# AGENT CONTEXT — Specific guidance for AI coding agents
# Purpose: This is the highest-value section. The items here represent
#          hard-won knowledge that prevents agents from making the
#          mistakes that humans have already made in this codebase.
#          Keep this section current — it degrades fast.
# ──────────────────────────────────────────────────────────────────────
agent_context:
  read_first:
    # [REQUIRED] Files an agent must read before starting any task.
    # List the minimum set that gives maximum orientation.
    # Example: ["types/index.ts", "lib/anthropic/intent-prompt.ts"]
    - "[REQUIRED] path/to/critical/file — why to read it first"

  gotchas:
    # [REQUIRED] Non-obvious facts that will cause an AI agent to make
    # mistakes if not known upfront. These are the landmines.
    # Be concrete and specific — vague gotchas are useless.
    # Example: "Google OAuth tokens expire after 1 hour and are not
    # automatically refreshed — all Drive calls will return 401 if the
    # user has been on the page for >1h without a page reload."
    - "[REQUIRED] Specific, concrete gotcha an agent would not infer from reading code"

  safe_to_modify:
    # [OPTIONAL] Areas that are straightforward to change without
    # cascading effects. Helps an agent work confidently.
    - "[OPTIONAL] File or area that is safe to change freely"

  handle_with_care:
    - area: "[OPTIONAL] File or system area requiring extra caution"
      reason: >
        Why this is risky. What could go wrong? What should the agent
        verify before and after touching this area?

  task_guidance:
    adding_features: >
      [OPTIONAL] The expected sequence of steps to add a new feature
      to this codebase. Which files to create and modify, what patterns
      to follow, what to verify afterwards.
    debugging: >
      [OPTIONAL] Where to look first when something breaks. Key log
      sources, common failure modes, useful diagnostic commands.
    refactoring: >
      [OPTIONAL] Approach for refactoring. What is safe to change
      freely, what needs coordination, what must never be broken.

# ──────────────────────────────────────────────────────────────────────
# CURRENT STATE — Live status of the project
# Purpose: Agents are often asked to 'continue work' without context.
#          This section bridges that gap. Update it regularly —
#          an outdated current_state is worse than none.
# ──────────────────────────────────────────────────────────────────────
current_state:
  as_of: >
    [REQUIRED] Date this section was last updated — YYYY-MM-DD format.
    An agent should treat information here as accurate as of this date.

  summary: >
    [REQUIRED] 1–3 sentences. Where is the project right now?
    What phase of development? What was just completed?
    What is the immediate focus?

  known_issues:
    - description: "[OPTIONAL] What the issue is and where it manifests"
      severity: "low | medium | high | critical"
      workaround: "How to work around it until properly fixed"

  in_progress:
    - feature: "[OPTIONAL] What is actively being built"
      status: "Brief status — where it stands right now"

  next_priorities:
    # [OPTIONAL] Ordered list. An agent picking up autonomous work
    # should start from item 1 unless instructed otherwise.
    - "[OPTIONAL] Next most important thing to work on"
`;
